---
- name: Setup homelab compute node
  hosts: localhost
  become: true

  vars:
    homelab_folders:
      - /srv/docker
      - /srv/data
      - /srv/backups
      - /srv/config
    ssh_user: "{{ ansible_user_id }}"

  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ssh_user }}"
        groups: docker
        append: true

    - name: Ensure homelab base folders exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0755'
      loop: "{{ homelab_folders }}"

    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present
        update_cache: yes

    - name: Enable unattended-upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^APT::Periodic::Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "1";' }
        - { regexp: '^APT::Periodic::Unattended-Upgrade', line: 'APT::Periodic::Unattended-Upgrade "1";' }
