services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.websecure.http.tls.certResolver=cloudflare"
      - "--entryPoints.websecure.http.tls.domains[0].main=gt3.dev"
      - "--entryPoints.websecure.http.tls.domains[0].sans=*.gt3.dev"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=acme@gt3.dev"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
    volumes:
      - "/volume1/Software/Docker-Appdata/traefik/dynamic:/etc/traefik/dynamic:ro"
      - "/volume1/Software/Docker-Appdata/traefik/letsencrypt:/letsencrypt"
